### ISSUE TITLE
沒辦法npm start 成功？

### ISSUE THREAD

**Issue by daubas** [g0v/g0v.tw#136]
請問，
fork網站試著npm start，
但一直無法成功，
請問有人可以知道是怎麼回事嗎？
下面是我的npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/nvm/0.27.1/versions/node/v4.1.2/bin/node',
1 verbose cli   '/usr/local/opt/nvm/versions/node/v4.1.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart g0v.tw@0.0.1
6 info start g0v.tw@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info g0v.tw@0.0.1 Failed to exec start script
9 verbose stack Error: g0v.tw@0.0.1 start: `gulp dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/nvm/0.27.1/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/nvm/0.27.1/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid g0v.tw@0.0.1
11 verbose cwd /Volumes/Apple HDD 500GB/Coding/nodejs/otsite/g0v.tw
12 error Darwin 14.5.0
13 error argv "/usr/local/Cellar/nvm/0.27.1/versions/node/v4.1.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.2/bin/npm" "start"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error g0v.tw@0.0.1 start: `gulp dev`
17 error Exit status 1
18 error Failed at the g0v.tw@0.0.1 start script 'gulp dev'.
18 error This is most likely a problem with the g0v.tw package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp dev
18 error You can get their info via:
18 error     npm owner ls g0v.tw
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by daubas** [comment]
自己回答，
似乎是最近LiveScript改版把全部都改成小寫livescript造成的問題，
把所有版本的livescript砍掉重裝就執行成功了。

**Comment by clkao** [comment]
Do we need to update package.ls ?

**Comment by daubas** [comment]
hello,
I found its bcz the update of livescript.
Tks for the concerning :)


Chia-liang Kao <notifications@github.com> 於 2015年10月13日 星期二寫道：

> Do we need to update package.ls ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g0v/g0v.tw/issues/136#issuecomment-147580584>.
>


-- 
陳思翰
0919523166
