### ISSUE TITLE
g0v官網導覽列-201608

### ISSUE THREAD

**Issue by NellLin** [g0v/g0v.tw#153]
首頁 http://g0v.tw/zh-TW/index.html

關於
-關於g0v http://g0v.tw/zh-TW/about.html
-聯繫我們 http://g0v.tw/zh-TW/contact.html
-媒體報導 http://g0v.tw/zh-TW/media.html
-Blog http://blog.g0v.tw/
-收支明細 http://g0v.tw/zh-TW/transaction.html

如何參與
-如何參與 http://g0v.tw/zh-TW/transaction.html
-FB後勤中心 https://www.facebook.com/groups/g0v.general/
-開發共筆 https://g0v.hackpad.com/
-g0v 開放資料平臺 https://g0v.hackpad.com/
-常見問題 http://g0v.tw/zh-TW/faq.html

成果列表 http://g0v.tw/zh-TW/projects.html

g0v 活動
-活動介紹 http://g0v.tw/zh-TW/actinfo.html
-活動紀錄 http://g0v.tw/zh-TW/actinfo.html
-演講資訊 http://g0v.tw/zh-TW/talk.html

**Comment by ipaaa** [comment]
關於：補宣言一頁
@kcliu 
-關於g0v http://g0v.tw/zh-TW/about.html
-零時政府宣言 http://g0v.tw/zh-TW/manifesto.html
-聯繫我們 http://g0v.tw/zh-TW/contact.html
-媒體報導 http://g0v.tw/zh-TW/media.html
-Blog http://blog.g0v.tw/
-收支明細 http://g0v.tw/zh-TW/transaction.html

**Comment by kcliu** [comment]
@ipaaa 如何參與的連結跟收支明細一樣嗎?

**Comment by kcliu** [comment]
活動介紹跟活動紀錄連結一樣？

**Comment by kcliu** [comment]
開發共筆 https://g0v.hackpad.com/
g0v 開放資料平臺 https://g0v.hackpad.com/

連結又一樣了XD

**Comment by ipaaa** [comment]
* 活動紀錄那頁 hacklog.html 先不要放 menu 好了
* g0v 開放資料平台砍了吧.... 那時大概沒人知道「共筆」，亂取的

**Comment by ipaaa** [comment]
@kcliu 
如何參與 http://g0v.tw/zh-TW/join.html
收支明細 http://g0v.tw/zh-TW/transaction.html
兩個不一樣呀 QQ
