### ISSUE TITLE
remove bootstrap css

### ISSUE THREAD

**Issue by clkao** [g0v/g0v.tw#65]
now are are in semantic-ui land, we can get rid of bootstrap css. however the basic reset (font, body margin etc) should remain

**Comment by yhsiang** [comment]
I found just img reset will effect
```
img {
  max-width: 100%;
  height: auto;
  vertical-align: middle;
  border: 0;
  -ms-interpolation-mode: bicubic;
}
```

**Comment by yhsiang** [comment]
這個 issue 一年了 終於可以解掉了 :rainbow:
